<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ChatbotMVC</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Providers\MySqlProvider.cs" />
    <Compile Remove="Data\Providers\PostgreSqlProvider.cs" />
    <Compile Remove="Data\Providers\SQLiteProvider.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
